import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

const inter = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop > Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       {children}
      </body>
    </html>
  );
}
